#src/federatedscope/core/configs/cfg_data.py
#src/federatedscope/core/configs/cfg_model.py
# Whether to use GPU
use_gpu: True

# Deciding which GPU to use
device: 5
seed: 10
# Federate learningg related options
federate:
  # `standalone` or `distributed`
  mode: 'standalone'
  # Evaluate in Server or Client test set
  make_global_eval: True
  # Number of dataset being split
  client_num: 3
  # Number of communication round
  total_round_num: 80
  method: fedavg

fedsageplus:
  num_pred: 5
  gen_hidden: 64
  hide_portion: 0.5
  fedgen_epoch: 0 #pre_train
  loc_epoch: 3
  a: 1.0
  b: 1.0
  c: 1.0
# Dataset related options
data:
  # Root directory where the data stored
  root: data/
  # Dataset name
  type: tfinance
  # Use Louvain algorithm to split `Cora`
  splitter: 'random_partition'
  splitter_delta: 20
#  splitter_args: [{'alpha': 0.5}]
  dgl: False
  anomaly_type: 'c'
dataloader:
  # Type of sampler
  type: pyg
  # Use fullbatch training, batch_size should be `1`
  batch_size: 100

# Model related options
model:
  # Model type
  type: anemone #cola #anemone
  # Hidden dim
  hidden: 64
  # Dropout rate
  dropout: 0.3
  # Number of Class of `Cora`，'citeseer':6
  out_channels: 6
  # cola
  subgraph_size: 4
  negsamp_ratio: 1
  verbose: True
  #The amount of contamination of the data set
  contamination: 0.1
  return_confidenc: True
  # anemone
  negsamp_ratio_patch: 1
  negsamp_ratio_context: 1
  alpha: 1
  test_rounds: 100
#  lr: 1e-3
#  weight_decay: 1e-5

# Criterion related options
criterion:
  # Criterion type
  type: 'BCEWithLogitsLoss'

# Trainer related options
trainer:
  # Trainer type
  type: fedAnemone #nodefullbatch_trainer #fedgod

# Train related options
train:
  # Number of local update steps
  local_update_steps: 4
  # Optimizer related options
  optimizer:
    # Learning rate
    lr: 0.0015
    # Weight decay
    weight_decay: 0
    # Optimizer type
    type: Adam #SGD

# Evaluation related options
eval:
  # Frequency of evaluation
  freq: 10
  # Evaluation metrics, accuracy and number of correct items
  metrics: ['roc_auc','acc']
  best_res_update_round_wise_key: test_roc_auc
  split: ['test']

wandb:
  use: False
  name_project: "fedcola"
  name_user: "huifa"